vulnerabilities:
  - id: CVE-2024-21538
    statement: Temporary exception for upstream OpenClaw v2026.2.19 dependency graph; re-evaluate on next upstream bump.
    expired_at: 2026-04-15
    paths:
      - package.json

  - id: CVE-2025-64756
    statement: Temporary exception for upstream OpenClaw v2026.2.19 dependency graph; re-evaluate on next upstream bump.
    expired_at: 2026-04-15
    paths:
      - package.json

  - id: CVE-2026-26996
    statement: Temporary exception for upstream OpenClaw v2026.2.19 dependency graph; re-evaluate on next upstream bump.
    expired_at: 2026-04-15
    paths:
      - package.json

  - id: CVE-2026-23745
    statement: Temporary exception for upstream OpenClaw v2026.2.19 dependency graph; re-evaluate on next upstream bump.
    expired_at: 2026-04-15
    paths:
      - package.json

  - id: CVE-2026-23950
    statement: Temporary exception for upstream OpenClaw v2026.2.19 dependency graph; re-evaluate on next upstream bump.
    expired_at: 2026-04-15
    paths:
      - package.json

  - id: CVE-2026-24842
    statement: Temporary exception for upstream OpenClaw v2026.2.19 dependency graph; re-evaluate on next upstream bump.
    expired_at: 2026-04-15
    paths:
      - package.json

  - id: CVE-2026-26960
    statement: Temporary exception for upstream OpenClaw v2026.2.19 dependency graph; re-evaluate on next upstream bump.
    expired_at: 2026-04-15
    paths:
      - package.json
